### ISSUE TITLE
Realtime Problem 

### ISSUE THREAD

**Issue by KhaledAld** [SkygearIO/chat-SDK-iOS#235]
Hi

**i'm using skygear server on my local**

> the owner of conversation only receive message but other only send message

when i send message between two device the message is received to first device and appear in ui <br>
but when send from second device the message not appear and not received
<br>
any body have this problem ???

**Comment by tensiuyan** [comment]
@KhaledAld do you mean when you send message from device A, device B can receive the message. However when you send message from device B, device A fails to receive the message?

What's your server & SDK version?

**Comment by KhaledAld** [comment]
@tensiuyan  
yes when send message from device B to  device A it fails to receive the message.

and i have another question 
what is the path of APSN Certificate (.pem file ), i use docker-comose.yml file to run skygear server 
and how to enable push Notification when send message in chat ??

**Comment by tensiuyan** [comment]
@KhaledAld could you please let me know -

- which SDK is device A using?
- which SDK is device B using?

About the APSN certificate question, I have answered it in another issue.

**Comment by KhaledAld** [comment]
SDK on all devices is  SKYKit/Core (~> 1.3.1)
now it's work fine 
but push notifications is not work on local 
and now work on portal when send new message (there is notification received to participant person)

**Comment by tensiuyan** [comment]
@KhaledAld Cool! We suggest you using a newer SDK (i.e. 1.6.2) since there are quite a few bug fixes in between.

For the push notification issue, please refer to this discussion thread: https://discuss.skygear.io/t/example-for-skygear-environment-variables/157/2

closing this issue since the problem is solved.

**Comment by KhaledAld** [comment]
i still have this error !!!!!!!!!!
skygear able to send push notification because APNS is not configured or there was a problem configuring the APNS.
